# Generated by Django 4.2.23 on 2025-07-25 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="boss",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="subordinates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Boss",
            ),
        ),
    ]
