# Generated by Django 4.2.23 on 2025-07-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0003_user_full_name_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
    ]
