# Generated by Django 4.2.23 on 2025-08-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0004_remove_user_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
