# Generated by Django 4.2.23 on 2025-08-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_alter_task_created_at_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
